In [1]:
# perkalian matriks array

import numpy as np

A = np.array([[0,8],[1,2],[6,4]])
B = np.array([[4,2],[2,0],[1,2]])

perkalian = A * B
print(perkalian)

[[ 0 16]
 [ 2  0]
 [ 6  8]]


In [3]:
# pengurangan matriks array

import numpy as np

A = np.array([[0,8],[1,2],[6,4]])
B = np.array([[4,2],[2,0],[1,2]])

pengurangan = A - B
print(pengurangan)

[[-4  6]
 [-1  2]
 [ 5  2]]


In [4]:
# transpose matriks array

import numpy as np 
A = np.array([[4,2],[2,0],[1,2]])

transpose_A = np.transpose(A)
print(transpose_A)

[[4 2 1]
 [2 0 2]]


In [28]:
# invers matriks array

import numpy as np

A = np.array([[4,2],[2,0]])

invers_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print("invers dari matriks A:", invers_A)


invers matriks A:
invers dari matriks A: [[ 0.   0.5]
 [ 0.5 -1. ]]


In [29]:
# determinan matriks array

import numpy as np
A = np.array([[4,2],[2,0]])

determinant_A = np.linalg.det(A)
print("determinan dari matriks A:", determinant_A)

determinan dari matriks A: -4.0
